apiVersion: v1
kind: Service
metadata:
  name: research-assistant-service
spec:
  type: NodePort
  selector:
    app: research-assistant
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080