version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333

  assistant:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./chat_history:/app/chat_history
    depends_on:
      - qdrant
    environment:
      - QDRANT_URL=http://qdrant:6333

volumes:
  qdrant_data: