apiVersion: apps/v1
kind: Deployment
metadata:
  name: admissions-assistant-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admissions-assistant
  template:
    metadata:
      labels:
        app: admissions-assistant
    spec:
      containers:
      - name: admissions-assistant-container
        image: ai-admissions-assistant
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"